[package]
name = "calculate_extra_time"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
reqwest = {version = "0.12.15", features = ["blocking"]}
serde = "1.0.219"
serde_json = "1.0.140"
structopt = "0.3.26"
